# -*- coding: utf-8 -*-
"""scrapper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aaPt4z3BYabse-mwEuVjTwsKCjXCx06R
"""

pip install beautifulsoup4

import re

pip install requests

import requests
from bs4 import BeautifulSoup
req = requests.get("http://www.useams.org/")
soup = BeautifulSoup(req.content,"html.parser")
results=soup.find(id='address')
if results:
  print(results.text)
else:
  print('unavailable')

import pandas as pd
df=pd.read_csv('web.csv')

df

print(df.iloc[:,2])

for i in df.iloc[:,2]:
  print(i)

df1=df.iloc[:,2]
df1

df1=df1.dropna()

for i in df1:
  print(i)

import requests
from bs4 import BeautifulSoup
for i in df1:
  req = requests.get(i)
  soup = BeautifulSoup(req.content,"html.parser")
  results=soup.find(id='address')
  if results:
    print(results.text)
  else:
    print('unavailable')